prefecture_id = Prefecture.find_by(name: "北海道").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 旭川旭町店", address:"北海道旭川市旭町1条7-841-120", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 旭川永山パワーズ店", address:"北海道旭川市永山１２条４丁目119-46", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 網走店", address:"北海道網走市つくしケ丘2丁目3番2号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 岩見沢大和タウンプラザ店", address:"北海道岩見沢市大和1条8-3-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 恵庭店", address:"北海道恵庭市黄金南7丁目18-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 小樽店", address:"北海道小樽市住吉町2-7", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フレスポ帯広稲田店", address:"北海道帯広市稲田町南9線西11-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 帯広店", address:"北海道帯広市西18条北1-29-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 北見店", address:"北海道北見市中央三輪１丁目371番地20", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 釧路店", address:"北海道釧路市昭和中央3-3-7", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 釧路春採店", address:"北海道釧路市春採7-1-68", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ひばりが丘タウンプラザ店", address:"北海道札幌市厚別区厚別中央2条2—2—2 ひばりが丘タウンプラザ内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 札幌屯田店", address:"北海道札幌市北区屯田7条4-7-28", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 札幌清田店（10月14日移転OPEN）", address:"北海道札幌市清田区清田236-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール札幌平岡店（2016/8/21　閉店）", address:"北海道札幌市清田区平岡三条5-276-1 イオンモール札幌平岡 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イーアス札幌店", address:"北海道札幌市白石区東札幌3条1丁目1番1号 A街区2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 札幌PIVOT店※KIDSのみ標準取扱となります。", address:"北海道札幌市中央区南2条西4丁目11番地 PIVOT 7・8階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　札幌エスタ店", address:"北海道札幌市中央区北5条西2-1 エスタ（札幌ターミナルビル）　5階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 札幌澄川ミュンヘン大橋店", address:"北海道札幌市豊平区平岸1条22-2-5", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 札幌二十四軒店", address:"北海道札幌市西区二十四軒3条2-2-1", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "青森県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ドリームタウン青森浜田店", address:"青森県青森市浜田3-1-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ガーラモール店（2016/9/25　閉店）", address:"青森県青森市三好2-3-19 マエダ1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 青森三好店（10月14日移転OPEN）", address:"青森県青森市三好2丁目2番36", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 五所川原エルムの街店", address:"青森県五所川原市唐笠柳藤巻517-1 エルムの街ショッピングセンター内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 十和田店", address:"青森県十和田市大字相坂字小林22", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ シンフォニープラザ八戸沼館店", address:"青森県八戸市沼館4丁目4-8", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 八戸湊高台店", address:"青森県八戸市湊高台5-3-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 弘前城東店", address:"青森県弘前市大字早稲田3-1-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 弘前神田店", address:"青森県弘前市大字神田4丁目3-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ むつ苫生店", address:"青森県むつ市金曲1-2-6 苫生モール内", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "岩手県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 一関店", address:"岩手県一関市山目字泥田5-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 水沢カルチャーパークあてるい店", address:"岩手県奥州市水沢区佐倉河字東沖ノ目123", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンタウン釜石店", address:"岩手県釜石市港町二丁目1番1号 イオンタウン釜石3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 北上店", address:"岩手県北上市有田町7-10 Ｊプラザ", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 花巻店", address:"岩手県花巻市上小舟渡11-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 盛岡都南店", address:"岩手県盛岡市三本柳9地割40-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 盛岡インター店", address:"岩手県盛岡市前潟2-3-12", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール盛岡南店", address:"岩手県盛岡市本宮七丁目1番1号 イオンモール盛岡南 1階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "宮城県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 石巻蛇田店", address:"宮城県石巻市恵み野3丁目4番地56", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 古川南店", address:"宮城県大崎市古川穂波7丁目2番12号 アクロスプラザ古川南内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 気仙沼店", address:"宮城県気仙沼市東新城1丁目7番8", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大河原店", address:"宮城県柴田郡大河原町字広表28番地12", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 仙台アエル店", address:"宮城県仙台市青葉区中央1-3-1 アエル3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 南吉成店", address:"宮城県仙台市青葉区南吉成3-1-24 南吉成タウンプラザ内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 仙台泉店", address:"宮城県仙台市泉区市名坂字清水端200-5", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 長町南店", address:"宮城県仙台市太白区大野田1丁目1番8号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ララガーデン長町店", address:"宮城県仙台市太白区長町7丁目20番5号 ララガーデン長町 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アクロスプラザ幸町店", address:"宮城県仙台市宮城野区大梶11-15", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 若林荒井店", address:"宮城県仙台市若林区伊在字屋敷41", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 佐沼店", address:"宮城県登米市迫町佐沼字萩洗2-12-5", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール名取店", address:"宮城県名取市杜せきのした五丁目3番地の1 イオンモール名取3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール利府店", address:"宮城県宮城郡利府町利府字新屋田前22 イオンモール利府", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "秋田県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール秋田店", address:"秋田県秋田市御所野地蔵田1-1-1 イオンモール秋田1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 秋田茨島店", address:"秋田県秋田市茨島1丁目1番35", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンタウン大館西店", address:"秋田県大館市根下戸新町18-80 イオンタウン大館西内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ メルシティ潟上店", address:"秋田県潟上市飯田川飯塚字上堤敷76番10", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 秋田アクロス能代店", address:"秋田県能代市字寺向80 ショッピングタウンアクロス能代", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フレスポ本荘店", address:"秋田県由利本荘市石脇字田頭162", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フレスポ横手店", address:"秋田県横手市安田字向田185 フレンドリースポット横手内", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "山形県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 新庄店", address:"山形県新庄市五日町字清水川1286-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール天童店", address:"山形県天童市芳賀土地区画整理事業地内34街区 イオンモール天童1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール三川店", address:"山形県東田川郡三川町大字猪子字和田庫128-1 イオンモール三川　1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 東根店", address:"山形県東根市中央南二丁目2番1号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フレスポ山形北店", address:"山形県山形市嶋北2丁目5番17号 フレスポ山形北", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 蔵王成沢店", address:"山形県山形市成沢西1-6-8", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール山形南店", address:"山形県山形市若宮三丁目7-8 イオンモール山形南", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 米沢店", address:"山形県米沢市徳町141", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "福島県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 会津若松アピオ店", address:"福島県会津若松市町北町大字始字宮前27番 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ いわき小名浜店", address:"福島県いわき市小名浜岡小名字沖32-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ いわき平店", address:"福島県いわき市平谷川瀬字双藤町37", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 郡山大槻店", address:"福島県郡山市御前南一丁目68番地", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 郡山日和田フェスタ店", address:"福島県郡山市日和田町字小原22 フェスタ駐車場区画内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ メガステージ白河店", address:"福島県白河市字新高山26-1 メガステージ白河ＳＣ内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンタウン須賀川店", address:"福島県須賀川市仲の町116", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 福島黒岩店", address:"福島県福島市黒岩字素利町27-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 福島南沢又店", address:"福島県福島市八島田字琵琶渕83番", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 原町店", address:"福島県南相馬市原町区北原字境堀261 ビアフレスコ内", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "茨城県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ウェルサイト石岡店", address:"茨城県石岡市東大橋字中峯1937-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アクロスプラザ神栖店", address:"茨城県神栖市居切1455-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 古河店", address:"茨城県古河市上辺見368番地1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 高萩店", address:"茨城県高萩市安良川406", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アクロスガーデン筑西店", address:"茨城県筑西市布川1310-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ LALAガーデンつくば店", address:"茨城県つくば市小野崎字千駄苅278-1 LALAガーデンつくば内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イーアスつくば店", address:"茨城県つくば市研究学園5丁目19番　イーアスつくば2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール土浦店", address:"茨城県土浦市上高津367 イオンモール土浦 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 取手店（2016/8/28　閉店）", address:"茨城県取手市寺田遠藤前5001-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 那珂店", address:"茨城県那珂市菅谷2650-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンタウン水戸南店", address:"茨城県東茨城郡茨城町長岡3480-101", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 日立成沢店", address:"茨城県日立市中成沢町2-37-13", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ひたちなかニューポート店", address:"茨城県ひたちなか市新光町35-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール水戸内原店", address:"茨城県水戸市内原2丁目1番地 イオンモール水戸内原2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 水戸姫子店", address:"茨城県水戸市姫子1-826-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンタウン守谷店", address:"茨城県守谷市百合ケ丘3-249-1 2F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 竜ヶ崎ニュータウン店", address:"茨城県竜ヶ崎市藤ヶ丘1-1-1", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "栃木県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　アシコタウンあしかが店", address:"栃木県足利市大月町3番2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ インターパークスタジアム店", address:"栃木県宇都宮市インターパーク4-2-3 インターパークスタジアム", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 宇都宮戸祭店", address:"栃木県宇都宮市下戸祭2丁目20番9号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 宇都宮鶴田店", address:"栃木県宇都宮市鶴田町3493-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 宇都宮今泉店", address:"栃木県宇都宮市元今泉2-22-9", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イトーヨーカドー宇都宮店", address:"栃木県宇都宮市陽東6-2-1 ベルモール内イトーヨーカドー2F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大田原店", address:"栃木県大田原市美原1-5-44", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ おやまゆうえんハーヴェストウォーク店", address:"栃木県小山市喜沢1475", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 氏家店", address:"栃木県さくら市卯の里2-26-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 佐野店", address:"栃木県佐野市鐙塚町167-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 石橋店", address:"栃木県下野市下古山2952-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 栃木店", address:"栃木県栃木市箱森町36番35号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 今市店", address:"栃木県日光市豊田44-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 真岡店", address:"栃木県真岡市上高間木3-5-1", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "群馬県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 安中店", address:"群馬県安中市岩井2468-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 伊勢崎店", address:"群馬県伊勢崎市連取町3093-17", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ スマーク伊勢崎店", address:"群馬県伊勢崎市西小保方町368 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ジョイフル新田店", address:"群馬県太田市新田市野井町592-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 太田店", address:"群馬県太田市新井町326-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール太田店", address:"群馬県太田市石原町81 イオンモール太田1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ マーケットシティ桐生店", address:"群馬県桐生市相生町1-124-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 渋川有馬店", address:"群馬県渋川市有馬字芦田141-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 高崎下之城店", address:"群馬県高崎市下之城町182-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 高崎問屋町店", address:"群馬県高崎市問屋町2-11-5", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール高崎店", address:"群馬県高崎市棟高町1400 イオンモール高崎 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 高崎モントレー店", address:"群馬県高崎市八島町222番地 高崎駅ビル・モントレー4階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 館林店", address:"群馬県館林市富士原町字富士原前1089-9", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 富岡店", address:"群馬県富岡市富岡字北畠1888-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 沼田店", address:"群馬県沼田市上原町1756-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 藤岡店", address:"群馬県藤岡市上大塚313", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 天川大島店", address:"群馬県前橋市天川大島町1-2-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ガーデン前橋店", address:"群馬県前橋市小屋原町472-1 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 前橋総社店", address:"群馬県前橋市総社町高井字十郎89-1", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "埼玉県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アリオ上尾店", address:"埼玉県上尾市大字壱丁目367番地  アリオ上尾1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 三芳店", address:"埼玉県入間郡三芳町藤久保652-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール春日部店", address:"埼玉県春日部市下柳420-1 イオンモール春日部 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ララガーデン春日部店", address:"埼玉県春日部市南1-1-12010 ララガーデン春日部 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ララガーデン川口店", address:"埼玉県川口市宮町18-9 ララガーデン川口1階1180", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール川口店", address:"埼玉県川口市安行領根岸3180 イオンモール川口3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ そごう川口店", address:"埼玉県川口市栄町3-5-1 そごう川口店7階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール川口前川店", address:"埼玉県川口市前川1-1-11-201", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 川越店", address:"埼玉県川越市大字石田字八ツ島町252番地", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 川越的場店", address:"埼玉県川越市的場新町14-6", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アトレマルヒロ川越店", address:"埼玉県川越市脇田町105番地  アトレマルヒロ川越 5階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 北本店", address:"埼玉県北本市深井6-87", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アリオ鷲宮店", address:"埼玉県久喜市久本寺字谷田7-1 アリオ鷲宮1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ モラージュ菖蒲店", address:"埼玉県久喜市菖蒲町菖蒲6005番地1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 熊谷ニットーモール店", address:"埼玉県熊谷市銀座2丁目245番地 熊谷ニットーモール2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンレイクタウンｍｏｒｉ店", address:"埼玉県越谷市レイクタウン3丁目1番地1 イオンレイクタウンmori 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 浦和コルソ店", address:"埼玉県さいたま市浦和区高砂1-12-1 コミュニティプラザ コルソ3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　コクーンシティ店", address:"埼玉県さいたま市大宮区吉敷町四丁目263-1 コクーン2 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ルミネ大宮店", address:"埼玉県さいたま市大宮区錦町630 ルミネ2 4階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ディラ大宮駅店", address:"埼玉県さいたま市大宮区錦町630 JR大宮駅北改札内", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "千葉県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 千葉旭店", address:"千葉県旭市イ川端2787", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ シャポー市川店", address:"千葉県市川市市川1-1-1 シャポー市川 B1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 市川コルトンプラザ店", address:"千葉県市川市鬼高1-1-1 ニッケコルトンプラザイースト館3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 市川妙典店", address:"千葉県市川市妙典3-20-6", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アリオ市原店", address:"千葉県市原市更級四丁目3番2 アリオ市原　1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ジョイフル千葉ＮＴ店", address:"千葉県印西市牧の原2-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アトレ新浦安店", address:"千葉県浦安市入船1-1-1 アトレ新浦安2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ セブンパークアリオ柏店", address:"千葉県柏市大島田950-1 セブンパーク　アリオ柏　2Ｆ", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 柏モディ店", address:"千葉県柏市柏1-2-26 柏モディ　4階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 柏増尾台店", address:"千葉県柏市中原2-2-3　1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール柏店", address:"千葉県柏市豊町2-5-25", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ららぽーと柏の葉店", address:"千葉県柏市若柴175 ららぽーと柏の葉2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 新鎌ヶ谷店", address:"千葉県鎌ケ谷市新鎌ヶ谷二丁目14番30号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 木更津店", address:"千葉県木更津市ほたる野4-1-17", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 館山店", address:"千葉県館山市湊201-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ペリエ稲毛店", address:"千葉県千葉市稲毛区稲毛東3-19-11 ペリエ稲毛 1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオン千葉長沼店", address:"千葉県千葉市稲毛区長沼町330-50 イオン千葉長沼店2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ホームズ蘇我店", address:"千葉県千葉市中央区川崎町55-3 ホームズ蘇我店2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ そごう千葉オーロラモールジュンヌ店", address:"千葉県千葉市中央区新町1001番地 そごう千葉店・オーロラモールジュンヌＢ1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンタウンおゆみ野店", address:"千葉県千葉市緑区おゆみ野南5-37-1  イオンタウンおゆみ野　2階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "東京都").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 昭島モリタウン店", address:"東京都昭島市田中町562-1 昭島モリタウン東館2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 足立入谷店", address:"東京都足立区入谷1-2-8", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 北千住マルイ店（10月28日OPEN）", address:"東京都足立区千住3-92 北千住マルイ6階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ルミネ北千住店", address:"東京都足立区千住旭町42-2 ルミネ北千住6階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 亀有店", address:"東京都足立区中川4-30-15", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アリオ西新井店", address:"東京都足立区西新井栄町1丁目20番1号 アリオ西新井 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ LaLaテラス南千住店", address:"東京都荒川区南千住4-7-2 LaLaテラス南千住 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ セブンタウン小豆沢店", address:"東京都板橋区小豆沢3丁目9番5号 セブンタウン小豆沢 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 板橋駅前本通り店", address:"東京都板橋区板橋1-33-8", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 板橋四ツ葉店", address:"東京都板橋区四葉2-10-6", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 稲城矢野口店", address:"東京都稲城市矢野口483-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 江戸川一之江店", address:"東京都江戸川区二之江町1385", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ホームズ葛西店", address:"東京都江戸川区東葛西9-3-6 ホームズ葛西店2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 西瑞江店", address:"東京都江戸川区瑞江3-41-4", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 青梅店", address:"東京都青梅市大門2丁目186-1番地", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 羽田空港第１ビル店", address:"東京都大田区羽田空港3-3-2 第1旅客ターミナルビル1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アトレ大森店", address:"東京都大田区大森北1-6-16 アトレ大森店 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大森北店", address:"東京都大田区大森北 四丁目11番5号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 上池台店", address:"東京都大田区上池台5-23-5", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 東急プラザ蒲田店", address:"東京都大田区西蒲田7-69-1 東急プラザ蒲田　5F", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "神奈川県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 厚木インター店", address:"神奈川県厚木市岡田3030番地", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 本厚木ミロード店", address:"神奈川県厚木市中町2-2-1 ミロードII 6階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　ビナフロント海老名店", address:"神奈川県海老名市中央1-2-2 ビナフロント3・4F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 小田原富水店", address:"神奈川県小田原市新屋28-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フレスポ小田原シティーモール店", address:"神奈川県小田原市前川120 フレスポ小田原シティーモール南館2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大船ルミネウィング店", address:"神奈川県鎌倉市大船1-4-1 ルミネウィング5階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 新百合丘オーパ店", address:"神奈川県川崎市麻生区上麻生1-1-1 新百合丘オーパ6階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アトレ川崎店（9月16日OPEN）", address:"神奈川県川崎市川崎区駅前本町26-1 アトレ川崎5階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 川崎ダイス店", address:"神奈川県川崎市川崎区駅前本町8 ダイス3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ラゾーナ川崎店", address:"神奈川県川崎市幸区堀川町72-1 ラゾーナ川崎1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ マルイファミリー溝口店", address:"神奈川県川崎市高津区溝口1-4-1 マルイファミリー溝口6階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ川崎市民プラザ通り店", address:"神奈川県川崎市高津区新作1-8-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 武蔵中原店", address:"神奈川県川崎市中原区上小田中3-7-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 武蔵小杉東急スクエア店", address:"神奈川県川崎市中原区小杉町3-472 武蔵小杉東急スクエア4階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 相模原中央店（10月21日移転OPEN）", address:"神奈川県相模原市中央区中央1-15-7", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 星が丘店（2016/10/20　閉店）", address:"神奈川県相模原市中央区星が丘4-16-14", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 橋本駅店", address:"神奈川県相模原市緑区橋本6-1-25 JR橋本駅改札外", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ミウィ橋本店", address:"神奈川県相模原市緑区橋本3-28-1 ミウィ橋本　4階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ホームズ相模原店（2016/10/20　閉店）", address:"神奈川県相模原市南区古淵2-9-1 ホームズ相模原店1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 相模大野ステーションスクエア店", address:"神奈川県相模原市南区相模大野3-8-1 相模大野ステーションスクエアB館5階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "新潟県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 柏崎店", address:"新潟県柏崎市東柳田40", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 燕三条店", address:"新潟県三条市大字下須頃187番", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 新発田店", address:"新潟県新発田市富塚町2-20-22", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 上越店", address:"新潟県上越市富岡3442-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アクロスプラザ長岡店", address:"新潟県長岡市沖田1丁目16番地", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ リバーサイド千秋店", address:"新潟県長岡市千秋2丁目278番地 リバーサイド千秋（アピタ長岡） 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 新津店", address:"新潟県新潟市秋葉区新津5163番地-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール新潟南店", address:"新潟県新潟市江南区下早通柳田1-1-1 イオンモール新潟南 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ラブラ万代店", address:"新潟県新潟市中央区万代1-5-1 ラブラ万代4階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 女池店", address:"新潟県新潟市中央区女池上山二丁目1番14号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 亀貝店", address:"新潟県新潟市西区亀貝3327番地", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フレスポ赤道店", address:"新潟県新潟市東区上王瀬町2-46", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "富山県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イータウン大島店", address:"富山県射水市本開発字代官免80番地", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 魚津店", address:"富山県魚津市上村木659-6", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 高岡インター店", address:"富山県高岡市上北島110-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 砺波店", address:"富山県砺波市太郎丸2-55", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 富山豊田店", address:"富山県富山市豊田本町一丁目  6番22号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 富山ファボーレ店", address:"富山県富山市婦中町下轡田165番地の１ フュチャーシティーファボーレ1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 富山山室店", address:"富山県富山市山室284-7", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "石川県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 金沢杜の里店", address:"石川県金沢市田上の里2丁目115番地", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ香林坊東急スクエア店", address:"石川県金沢市香林坊2-1-1 香林坊東急スクエア 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アピタタウン金沢ベイ店", address:"石川県金沢市無量寺4丁目91番地-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモールかほく店", address:"石川県かほく市内日角夕25番 イオンモールかほく 2F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 小松店", address:"石川県小松市平面町61-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 七尾店", address:"石川県七尾市藤橋町戌4-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 野々市店", address:"石川県野々市市三日市町45街区1", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "福井県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 武生店", address:"福井県越前市新保町2字6", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 敦賀店", address:"福井県敦賀市市野々町9-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フェアモール福井店", address:"福井県福井市大和田二丁目1230番地 フェアモール福井アピタ棟1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 福井運動公園前店", address:"福井県福井市加茂河原町30-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 福井灯明寺店", address:"福井県福井市灯明寺4丁目104", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "山梨県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ラザウォーク甲斐双葉店", address:"山梨県甲斐市志田字柿木645-1番地 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 甲府上阿原店", address:"山梨県甲府市上阿原町511-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンタウン山梨中央店", address:"山梨県中央市下河東400 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 富士吉田店", address:"山梨県富士吉田市上吉田6683", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 南アルプスビッグステージ店", address:"山梨県南アルプス市在家塚474", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "長野県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ あづみの穂高店", address:"長野県安曇野市穂高801-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 飯田店", address:"長野県飯田市鼎名古熊2501-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 伊那店", address:"長野県伊那市下新田3140番3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 上田店", address:"長野県上田市国分字上沖80-6", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ レイクウォーク岡谷店（9月2日OPEN）", address:"長野県岡谷市銀座1丁目1番5号 レイクウォーク岡谷　1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　佐久北インター店", address:"長野県小諸市大字御影新田2587-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 茅野店", address:"長野県茅野市ちの字本田2620-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 信州中野店", address:"長野県中野市大字吉田90-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 長野稲葉店", address:"長野県長野市大字稲葉字上千田沖329番3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 長野南店", address:"長野県長野市篠ノ井杵淵480-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アクロスプラザ長野北店", address:"長野県長野市檀田2-32-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 南松本店", address:"長野県松本市平田東3丁目1番2号", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "岐阜県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 恵那店", address:"岐阜県恵那市長島町中野247-999", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大垣店", address:"岐阜県大垣市島里2-25-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アクアウォーク大垣店", address:"岐阜県大垣市林町6-80-21 アクアウォーク大垣1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール各務原店", address:"岐阜県各務原市那加萱場町3-8 イオンモール各務原2Ｆ", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ オーキッドパーク店", address:"岐阜県岐阜市香蘭2-23 オーキッドパーク西棟2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 岐阜鷺山店", address:"岐阜県岐阜市下土居二丁目24番1号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ カラフルタウン岐阜店", address:"岐阜県岐阜市柳津町丸野3丁目3-6 カラフルタウン岐阜 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ マーゴ関店", address:"岐阜県関市倉知516 サンサンシティ・マーゴ2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フレスポ高山店", address:"岐阜県高山市天満町1丁目5番8", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 多治見店", address:"岐阜県多治見市光ヶ丘5丁目29-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 美濃加茂店", address:"岐阜県美濃加茂市山手町2-46", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ モレラ岐阜店", address:"岐阜県本巣市三橋1100番 1階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "静岡県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 伊東店", address:"静岡県伊東市吉田720-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ららぽーと磐田店", address:"静岡県磐田市高見丘1200番地 ららぽーと磐田2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 磐田店", address:"静岡県磐田市鳥之瀬24", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 御前崎店", address:"静岡県御前崎市池新田6038-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 掛川店", address:"静岡県掛川市大池480", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 御殿場店", address:"静岡県御殿場市東田中字便船塚1017-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ SHIZUOKA 109店", address:"静岡県静岡市葵区伝馬町6-1 5階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ MARK IS 静岡店", address:"静岡県静岡市葵区柚木191 MARK IS 静岡 2F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ エスパルスドリームプラザ店", address:"静岡県静岡市清水区港町1-7-15", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 静岡国吉田店", address:"静岡県静岡市駿河区国吉田2-1-5", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 静岡ＳＢＳ通り店", address:"静岡県静岡市駿河区豊田2-7-37", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 富士店", address:"静岡県富士市永田町2-96", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ サントムーン柿田川店", address:"静岡県駿東郡清水町伏見58番地1 サントムーン柿田川アネックス1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 函南店", address:"静岡県田方郡函南町間宮588-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 沼津店", address:"静岡県沼津市寿町7番1号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンタウン浜松葵店", address:"静岡県浜松市中区葵西3-25-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ザザシティ浜松店", address:"静岡県浜松市中区鍛冶町15 ザザシティ浜松西館1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 浜松入野店", address:"静岡県浜松市西区入野町9812-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール浜松志都呂店", address:"静岡県浜松市西区志都呂二丁目37番1号 イオンモール浜松志都呂3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ プレ葉ウォーク浜北店", address:"静岡県浜松市浜北区貴布祢1200番地 プレ葉ウォーク浜北2階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "愛知県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 新安城店", address:"愛知県安城市住吉町荒曽根43番地 1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 一宮今伊勢店", address:"愛知県一宮市今伊勢町本神戸字南新田1-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール木曽川店", address:"愛知県一宮市木曽川町黒田字南八ツケ池25-1 イオンモール木曽川 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ リーフウォーク稲沢店", address:"愛知県稲沢市長野7丁目1-2 リーフウォーク稲沢2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　アピタ稲沢店", address:"愛知県稲沢市天池五反田町1番地 アピタ稲沢1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 岡崎店", address:"愛知県岡崎市井田西町1-5", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ウイングタウン岡崎店", address:"愛知県岡崎市羽根町小豆坂3番地 ウイングタウン", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 岡崎竜美丘店", address:"愛知県岡崎市東明大寺町15-1 竜美丘ガーデンプレイス内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 尾張旭店", address:"愛知県尾張旭市南原山赤土200-10", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 高蔵寺センター店", address:"愛知県春日井市中央台1-4-4", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 春日井店", address:"愛知県春日井市六軒屋町西3-3-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 蒲郡店", address:"愛知県蒲郡市港町13-11", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ヴィアモール江南店", address:"愛知県江南市松竹町上野205番地 施設内2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 小牧店", address:"愛知県小牧市郷中1丁目239番地", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール東浦店", address:"愛知県知多郡東浦町大字緒川字旭13-2  イオンモール東浦2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 東海店", address:"愛知県東海市荒尾町福部78", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 中部国際空港店", address:"愛知県常滑市セントレア1-1 中部国際空港 旅客ターミナルビル4階レンガ通り", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール常滑店", address:"愛知県常滑市りんくう町2-20-3 イオンモール常滑1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 豊川御油店", address:"愛知県豊川市御油町 字八面横30", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 豊田GAZA店", address:"愛知県豊田市喜多町1-140 GAZA内3階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "三重県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 伊勢店", address:"三重県伊勢市御薗町長屋2932", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 桑名店", address:"三重県桑名市大字大仲新田10-3 桑名サンシパーク内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール桑名店", address:"三重県桑名市新西方1丁目22番地 イオンモール桑名 アンク専門店街 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンタウン鈴鹿店", address:"三重県鈴鹿市庄野羽山4-20-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 津島崎店", address:"三重県津市島崎町36", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 津ラッツ店", address:"三重県津市藤方716ベイスクエア津内 ラッツ 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 名張店", address:"三重県名張市希央台3番町24番地", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 松阪店", address:"三重県松阪市高町288", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 三重川越店", address:"三重県三重郡川越町大字高松37 川越ショッピングセンター内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 四日市日永店", address:"三重県四日市市日永東1-1-17", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "滋賀県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオン近江八幡店", address:"滋賀県近江八幡市鷹飼町190-9 イオン近江八幡 3F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 近江八幡店", address:"滋賀県近江八幡市鷹飼町北3-2-8", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フォレオ大津一里山店", address:"滋賀県大津市一里山7丁目1-1 2F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大津パルコ店", address:"滋賀県大津市打出浜14-30 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大津真野店", address:"滋賀県大津市真野5丁目35番16号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　イオンモール草津店", address:"滋賀県草津市新浜町300 イオンモール草津2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 草津エイスクエア店", address:"滋賀県草津市西渋川1丁目18番51号103号 エイスクエア・ノース1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンタウン湖南店", address:"滋賀県湖南市岩根4580（別棟）", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 長浜風の街店（10月28日移転OPEN）", address:"滋賀県長浜市八幡中山町526", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 西友長浜楽市店（2016/10/27　閉店）", address:"滋賀県長浜市八幡東町9-1 西友長浜楽市3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　イオンタウン彦根店", address:"滋賀県彦根市里根町24", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "京都府").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 宇治大久保店", address:"京都府宇治市大久保町北ノ山24-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 亀岡店", address:"京都府亀岡市篠町野条下川31", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール高の原店", address:"京都府木津川市相楽台1-1-1 イオンモール高の原 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 嵯峨野店", address:"京都府京都市右京区嵯峨野秋街道町51", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 京都ファミリー店", address:"京都府京都市右京区山ノ内池尻町1-1 京都ファミリー1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 西陣店", address:"京都府京都市上京区中立売通大宮西入新元町216", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 北大路ビブレ店", address:"京都府京都市北区小山北上総町49-1 北大路ビブレ3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 一乗寺店（10月21日OPEN）", address:"京都府京都市左京区一乗寺築田町43", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ カナート洛北店", address:"京都府京都市左京区高野西開町36 カナート洛北内2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 京都ヨドバシ店", address:"京都府京都市下京区烏丸通七条下ル東塩小路町590-2 京都ヨドバシ4階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 五条丹波口店", address:"京都府京都市下京区中堂寺南町128", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 京都駅八条口店", address:"京都府京都市下京区東塩小路高倉町8-3 アスティロード京都1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ミーナ京都店", address:"京都府京都市中京区河原町通三条下ル大黒町58番地 5階・6階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 上桂店", address:"京都府京都市西京区桂上野南町23", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ MOMOテラス店", address:"京都府京都市伏見区桃山町山ノ下32 MOMOテラス 2F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 伏見店", address:"京都府京都市伏見区竹田泓ノ川町1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール京都桂川店", address:"京都府京都市南区久世高田町376番1 イオンモール京都桂川3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモールＫＹＯＴＯ店", address:"京都府京都市南区西九条鳥居口町1番地 イオンモールKYOTO Ｓakura館3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ラクト山科店", address:"京都府京都市山科区竹鼻竹ノ街道町91", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンタウン久御山店", address:"京都府久世郡久御山町大字森小字大内337 イオンタウン久御山（旧ロックタウン久御山） 1階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "大阪府").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 南海なんば駅店", address:"大阪府大阪市中央区難波5丁目1番60 南海なんば駅3階コンコース", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ なんばウォーク店", address:"大阪府大阪市中央区難波一丁目虹の町３−７号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 池田店", address:"大阪府池田市鉢塚1-1-21", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 泉大津店", address:"大阪府泉大津市千原町2-21-16", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ いこらも～る泉佐野店", address:"大阪府泉佐野市下瓦屋2-2-77 いこらも～る泉佐野1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 関西エアポート店", address:"大阪府泉佐野市泉州空港北1 第一ターミナルビル3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ららぽーと和泉店", address:"大阪府和泉市あゆみ野4-4-7 ららぽーと和泉3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ コムボックス光明池店", address:"大阪府和泉市室堂町824-36 コムボックス光明池2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 茨木西河原店", address:"大阪府茨木市西河原2-19-16", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ あべのキューズモール店", address:"大阪府大阪市阿倍野区阿倍野筋1丁目6番1 あべのキューズモール 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 生野巽店", address:"大阪府大阪市生野区巽中1-16-6", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大丸梅田店", address:"大阪府大阪市北区梅田3-1-1 大丸梅田店13階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ヨドバシ梅田店", address:"大阪府大阪市北区大深町1-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　ekimo梅田店", address:"大阪府大阪市北区角田町8-6 大阪市営地下鉄御堂筋線梅田駅地下1階コンコース", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "UNIQLO OSAKA", address:"大阪府大阪市北区茶屋町1番32", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 城東関目店", address:"大阪府大阪市城東区関目3-1-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 住吉我孫子店", address:"大阪府大阪市住吉区我孫子西2-5-7", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 心斎橋店", address:"大阪府大阪市中央区心斎橋筋1丁目2番17号 B1-4階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 京阪シティモール店", address:"大阪府大阪市中央区天満橋京町1-1 京阪シティモール6階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ なんばCITY店", address:"大阪府大阪市中央区難波五丁目1番60号 2901区画", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "兵庫県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 明石ビブレ店", address:"兵庫県明石市大久保町ゆりのき通り1-3-2 明石ビブレ 4階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 赤穂店", address:"兵庫県赤穂市加里屋中洲1-11", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ あまがさきキューズモール店", address:"兵庫県尼崎市潮江一丁目3番1号 あまがさきキューズモール 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ つかしん店", address:"兵庫県尼崎市塚口本町4-8-1 ひがしまち 南館4階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 尼崎水堂店", address:"兵庫県尼崎市水堂町4-2-16", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール伊丹昆陽店", address:"兵庫県伊丹市池尻4-1-1 イオンモール伊丹昆陽 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール伊丹店", address:"兵庫県伊丹市藤ノ木1-1-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　太子店", address:"兵庫県揖保郡太子町東保字神田170-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 加古川ニッケパークタウン店（10月21日移転OPEN）", address:"兵庫県加古川市加古川町寺家町173-1 ニッケパークタウン専門店街　1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 加古川別府店", address:"兵庫県加古川市別府町石町92-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 川西西多田店", address:"兵庫県川西市矢問3-22-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 福崎店", address:"兵庫県神崎郡福崎町南田原3143-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール神戸北店", address:"兵庫県神戸市北区上津台8-1-1 イオン神戸北3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 神戸北町店", address:"兵庫県神戸市北区日の峰1-14-6", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大丸須磨店", address:"兵庫県神戸市須磨区中落合2-2-4 大丸須磨店3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ BRANCH 神戸学園都市店", address:"兵庫県神戸市垂水区小束山手2丁目2-1 BRANCH神戸学園都市　2F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 神戸三宮店", address:"兵庫県神戸市中央区三宮町1-5-16", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 神戸ハーバーランドｕｍｉｅ店", address:"兵庫県神戸市中央区東川崎町1-7-2 神戸ハーバーランドumie 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 神戸元町店", address:"兵庫県神戸市中央区元町通1丁目7-1 VEGAビル", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ブルメールＨＡＴ神戸店", address:"兵庫県神戸市中央区脇浜海岸通2-2-2", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "奈良県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 生駒店", address:"奈良県生駒市小明町250-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 橿原店", address:"奈良県橿原市葛本町801", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール橿原店", address:"奈良県橿原市曲川町7-20-1 イオンモール橿原 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 香芝店", address:"奈良県香芝市北今市7丁目304", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 西大和店", address:"奈良県北葛城郡河合町西山台522-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アクロスプラザ天理店", address:"奈良県天理市岩室町73-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 押熊店", address:"奈良県奈良市押熊町2269", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ならファミリー店（9月2日移転OPEN）", address:"奈良県奈良市西大寺東町2-4-1 ならファミリー4Ｆ", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール大和郡山店", address:"奈良県大和郡山市下三橋町741-246 イオンモール大和郡山2階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "和歌山県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 新宮店", address:"和歌山県新宮市佐野3-11-19", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 田辺店", address:"和歌山県田辺市上の山一丁目6番20号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 橋本彩の台店", address:"和歌山県橋本市あやの台1-50-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 紀伊川辺店", address:"和歌山県和歌山市川辺220 イズミヤスーパーセンター紀伊川辺店内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 国体道路店", address:"和歌山県和歌山市小雑賀704", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 紀の川店", address:"和歌山県和歌山市栄谷179-2", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "鳥取県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 倉吉店", address:"鳥取県倉吉市福庭町2-65", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール鳥取北店", address:"鳥取県鳥取市晩稲348番地 イオンモール鳥取北 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 米子新開店", address:"鳥取県米子市新開2-3-5", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "島根県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウン出雲店", address:"島根県出雲市大塚町650-1 東館 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 益田店", address:"島根県益田市高津7-18-20", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 松江店", address:"島根県松江市西津田1丁目9番37号", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "岡山県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 岡山中仙道店", address:"岡山県岡山市北区北長瀬表町2丁目13番15号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール岡山店", address:"岡山県岡山市北区下石井1-2-1 イオンモール岡山　4階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 岡山十日市店", address:"岡山県岡山市北区十日市西町8番23号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 原尾島店", address:"岡山県岡山市中区原尾島3丁目8番8号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　倉敷北畝店", address:"岡山県倉敷市北畝1丁目19番18号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 倉敷児島店", address:"岡山県倉敷市児島下の町2-1-50", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 倉敷平田店", address:"岡山県倉敷市平田615-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール倉敷店", address:"岡山県倉敷市水江1 イオンモール倉敷 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 津山店", address:"岡山県津山市小田中1443-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール津山店", address:"岡山県津山市河辺1000-1 イオンモール津山 1階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "広島県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ パルティフジ坂店", address:"広島県安芸郡坂町平成ヶ浜3-2-11", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール広島府中店", address:"広島県安芸郡府中町大須2-1-1 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 東尾道店", address:"広島県尾道市高須町字西新涯5766-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 呉レクレ店", address:"広島県呉市宝町2-50 レクレ2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　ゆめタウン廿日市店", address:"広島県廿日市市下平良二丁目2番-1 ゆめタウン廿日市", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 東広島店", address:"広島県東広島市西条御条町1-23", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 安佐南大町店", address:"広島県広島市安佐南区大町東3-15-22", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 広島八木店", address:"広島県広島市安佐南区八木1-21-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 広島八丁堀店", address:"広島県広島市中区胡町5-22 天満屋八丁堀ビル6F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 紙屋町サンモール店", address:"広島県広島市中区紙屋町2-2-18 紙屋町サンモール2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 広島アルパーク店", address:"広島県広島市西区草津新町2-26-1 アルパーク東棟1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 庚午店", address:"広島県広島市西区庚午中1-6-23", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウン広島店", address:"広島県広島市南区皆実町2丁目8-17 ゆめタウン広島 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 福山駅家店", address:"広島県福山市駅家町倉光141-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 福山新涯店", address:"広島県福山市西新涯2-10-17", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 福山明神店", address:"広島県福山市明神町1丁目10-25", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 三原店", address:"広島県三原市宮浦3-35-11", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 三次店", address:"広島県三次市南畑敷町239-3", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "山口県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フレスタモール岩国店", address:"山口県岩国市室の木1丁目2番38号 フレスタモールカジル岩国", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 宇部清水川店", address:"山口県宇部市恩田町3丁目1番3号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ シーモールエスト下関店", address:"山口県下関市竹崎町4-4-7 シーモールエスト2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 長府店", address:"山口県下関市長府才川1-600 サンタウン長府内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 徳山店", address:"山口県周南市周陽1-1-25", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 萩店", address:"山口県萩市大字土原24-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 光店", address:"山口県光市浅江4-1-7-2 浅江ショッピングセンター内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 防府店", address:"山口県防府市国衙5-8-8", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 山口店", address:"山口県山口市宮島町9番7号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめシティ新下関店", address:"山口県下関市伊倉新町3-1 ゆめシティ新下関3階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "徳島県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 阿南アピカ店", address:"徳島県阿南市西路見町堤外65-1 阿南ショッピングプラザ アピカ内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウン徳島店", address:"徳島県板野郡藍住町奥野字中須 ゆめタウン徳島", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 徳島藍住店", address:"徳島県板野郡藍住町東中富字長江傍示26-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 徳島沖浜店", address:"徳島県徳島市沖浜東1-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ そごう徳島店", address:"徳島県徳島市寺島本町西1-5 そごう徳島店 7階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "香川県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 宇多津店", address:"香川県綾歌郡宇多津町浜4番丁44-3", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウン高松店", address:"香川県高松市上天神町高田326-1 東館2、3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール高松店", address:"香川県高松市香西本町1-1 イオンモール高松 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 高松屋島店", address:"香川県高松市高松町2554-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ パワーシティレインボー店", address:"香川県高松市多肥下町1552番地11", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウン丸亀店", address:"香川県丸亀市新田町150 2階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "愛媛県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 今治店", address:"愛媛県今治市旭町3-2-6", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ エミフルMASAKI店", address:"愛媛県伊予郡松前町筒井850 エミフルMASAKI  1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　宇和島店", address:"愛媛県宇和島市祝森甲1664番", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大洲店", address:"愛媛県大洲市新谷乙405番1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 四国中央店", address:"愛媛県四国中央市妻鳥町1653-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フォレオにいはま店", address:"愛媛県新居浜市前田町3番2号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 松山久米店", address:"愛媛県松山市来住町818-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 松山谷町店", address:"愛媛県松山市谷町109", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 保免店", address:"愛媛県松山市保免中1-4-16", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "高知県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 高知介良店", address:"高知県高知市介良乙317-1 パワーセンター高知内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール高知店", address:"高知県高知市秦南町1‐4‐8 イオンモール高知 1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 土佐道路店", address:"高知県高知市城山町225", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 四万十ショッピングガーデン店", address:"高知県四万十市具同字八反田3193-1", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "福岡県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 甘木店", address:"福岡県朝倉市大字甘木字大鋸331-6", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 飯塚店", address:"福岡県飯塚市秋松866-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大野城御笠川店", address:"福岡県大野城市御笠川2-2-16", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウン大牟田店", address:"福岡県大牟田市旭町2丁目28-1 ゆめタウン大牟田SC 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 春日フォレストシティ店", address:"福岡県春日市星見ヶ丘1-80", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール福岡店", address:"福岡県糟屋郡粕屋町大字酒殿字老ノ木192-1 イオンモール福岡2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 福岡新宮店", address:"福岡県糟屋郡新宮町中央駅前2丁目5番1号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ チャチャタウン小倉店", address:"福岡県北九州市小倉北区砂津3-1-1 チャチャタウン小倉ショッピングセンター内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 曽根バイパス店", address:"福岡県北九州市小倉南区下貫2-1-22", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 折尾店", address:"福岡県北九州市八幡西区光明1-8-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウン久留米店", address:"福岡県久留米市新合川1-2-1 ゆめタウン久留米 2F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 久留米上津店", address:"福岡県久留米市藤光1-6-10", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 田川夏吉店", address:"福岡県田川市大字夏吉1418番1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 太宰府店", address:"福岡県太宰府市大佐野2丁目16番1号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　イオンモール筑紫野店", address:"福岡県筑紫野市立明寺434番地1 イオンモール筑紫野　2F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ショッパーズモールなかま店", address:"福岡県中間市上蓮花寺2-1-1 ショッパーズモールなかま西館1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール直方店", address:"福岡県直方市湯野原2丁目1番1号 イオン直方ショッピングセンター 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 長尾店", address:"福岡県福岡市城南区長尾1-13-34", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ミーナ天神店", address:"福岡県福岡市中央区天神4-3-8 ミーナ天神 5階・6階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ マリノアシティ福岡店", address:"福岡県福岡市西区小戸2-12-30", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "佐賀県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 唐津店", address:"佐賀県唐津市和多田大土井10番1号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 佐賀鍋島店", address:"佐賀県佐賀市鍋島町大字森田107-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウン佐賀店", address:"佐賀県佐賀市兵庫北5丁目14番1号 ゆめタウン佐賀 1F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 武雄店", address:"佐賀県武雄市武雄町大字昭和790", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "長崎県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アクロスプラザ諫早店", address:"長崎県諫早市久山町1271-2", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 大村松並店", address:"長崎県大村市松並2-894", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 佐世保大塔店", address:"長崎県佐世保市大塔町616-127", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 佐世保矢峰店", address:"長崎県佐世保市松原町26-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 島原店", address:"長崎県島原市北門町102-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウン夢彩都店", address:"長崎県長崎市元船町10-1 ゆめタウン夢彩都 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ みらい長崎ココウォーク店", address:"長崎県長崎市茂里町1番55号 みらい長崎ココウォーク 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ケイズタウン長崎時津店", address:"長崎県西彼杵郡時津町元村郷字岩崎832-1 2階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "熊本県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 天草本渡店", address:"熊本県天草市中村町2番13号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール宇城店", address:"熊本県宇城市小川町河江1-1 イオンモール宇城2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール熊本店", address:"熊本県上益城郡嘉島町大字上島字長池2232 2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　ゆめタウン光の森店", address:"熊本県菊池郡菊陽町光の森7丁目39-1 ゆめタウン光の森　2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ サンロードシティ人吉店", address:"熊本県球磨郡錦町西字打越715-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　北熊本店", address:"熊本県熊本市北区下硯川町字松作2100番1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ サンロードシティ熊本店", address:"熊本県熊本市東区東町3丁目3番３", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 熊南店", address:"熊本県熊本市南区十禅寺3-4-66", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウンはません店　※一時閉店しております。", address:"熊本県熊本市南区田井島1-2-1 ゆめタウンはません 3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウン八代店", address:"熊本県八代市建馬町3-1", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "大分県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ　アミュプラザおおいた店", address:"大分県大分市要町1番14号  アミュプラザおおいた3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ パークプレイス大分店", address:"大分県大分市公園通り西2丁目1番  パークプレイス大分1・2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 高城店", address:"大分県大分市高城本町6番8号", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ トキハわさだタウン店", address:"大分県大分市玉沢楠本755-1 トキハわさだタウン3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ トキハインダストリー店", address:"大分県佐伯市大字長谷字エビセキ10846-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フレスポ中津北店", address:"大分県中津市大字大新田287番１ フレスポ中津北SC1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 日田店", address:"大分県日田市大字友田802-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ゆめタウン別府店", address:"大分県別府市楠町382-7 ゆめタウン別府 3階", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "宮崎県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 小林店", address:"宮崎県小林市大字水流迫239-9", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 日南店", address:"宮崎県日南市吾田西4-7-28", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオン延岡ＳＣ店", address:"宮崎県延岡市旭町2丁目2-1 イオン延岡ショッピングセンター1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 日向店", address:"宮崎県日向市亀崎西1-62", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 都城店", address:"宮崎県都城市上川東4-5983", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ ニトリモール宮崎店", address:"宮崎県宮崎市源藤町東田454番地 ニトリモール内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 宮崎北店（2016/8/28　閉店）", address:"宮崎県宮崎市島ノ内6729-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール宮崎店", address:"宮崎県宮崎市新別府町江口862-1 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フェニックスガーデンうきのじょう店", address:"宮崎県宮崎市柳丸町165", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "鹿児島県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 姶良店", address:"鹿児島県姶良市西餅田3337-31", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 出水店", address:"鹿児島県出水市六月田町455", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 指宿店", address:"鹿児島県指宿市東方10847-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 鹿児島新栄店", address:"鹿児島県鹿児島市新栄町5-22", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 鹿児島草牟田店", address:"鹿児島県鹿児島市草牟田1-2-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ アミュプラザ鹿児島店", address:"鹿児島県鹿児島市中央町1-1 アミュプラザ鹿児島 B1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール鹿児島店", address:"鹿児島県鹿児島市東開町7番 イオンモール鹿児島　3階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フレスポジャングルパーク店", address:"鹿児島県鹿児島市与次郎1-11-1", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 鹿屋店", address:"鹿児島県鹿屋市笠之原町2101番地", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ フレスポ国分店", address:"鹿児島県霧島市国分広瀬2丁目4番1号 フレスポ国分 1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 薩摩川内店", address:"鹿児島県薩摩川内市御陵下町3290番1", prefecture_id: prefecture_id)
prefecture_id = Prefecture.find_by(name: "沖縄県").id
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオン具志川ＳＣ店", address:"沖縄県うるま市字前原幸崎原303 イオン具志川ショッピングセンター2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ はにんす宜野湾店", address:"沖縄県宜野湾市大山7-1400-16", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオン南風原店　※KIDSのみ旗艦店の取扱いとなります。", address:"沖縄県島尻郡南風原町字宮平264 イオン南風原　2F", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオンモール沖縄ライカム店", address:"沖縄県中頭郡北中城村アワセ土地区画整理事業区域内4街区 イオンモール沖縄ライカム2階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオン名護ＳＣ店", address:"沖縄県名護市字名護見取川原4472 イオン名護ショッピングセンター1階", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ 天久りうぼう楽市店", address:"沖縄県那覇市天久1-1-1 りうぼう施設内", prefecture_id: prefecture_id)
Shop.find_by(name: "UNIQLO").branches.create(name: "ユニクロ イオン那覇ＳＣ店", address:"沖縄県那覇市金城5-10-2 イオン那覇ショッピングセンター2階", prefecture_id: prefecture_id)
