# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  socket: /tmp/mysql.sock

development:
  <<: *default
  host:     localhost
  database: fsm_development
  username: root

test:
  <<: *default
  host:     localhost
  database: fsm_test
  username: root

staging:
  <<: *default
  host:     localhost
  database: fsm_staging
  username: root

production:
  adapter:  postgresql
  encoding: utf8
  host:     localhost
  database: ssm_app_production
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  pool:     5
  timeout:  5000
